### ISSUE TITLE
Overall feedback ook in feedback-veld van Attempt wegschrijven

### ISSUE THREAD

**Issue by allardnaber** [rijksuniversiteit-groningen/b2-AssessmentTools#108]
Use case: Talencentrum beoordeelt werkstukken op schrijfvaardigheid en geeft individuele feedback mbv essay-grading. Ze moeten echter ook rapporteren naar opdrachtgever, en willen hiertoe de overall feedback exporteren naar Excel, omdat daar op drie criteria de score van de student (CEFR levels A1/2, B1/2, C1/2) wordt gegeven. 
Als de overall feedback ook in het Attempt-veld wordt opgeslagen kunnen zij dit zelf, en hoef ik niets uit de database te vissen :)

**Comment by jasper-smit** [comment]
Er zal toch iemand dat attempt veld weer moeten lezen lijkt me

**Comment by allardnaber** [comment]
Ja het wordt aan de student gepubliceerd in de My Grades module (dus als je niet direct op je cijfer klikt). En het komt dus ook in de export naar Excel (Work offline)
