### ISSUE TITLE
Export submissions zonder header

### ISSUE THREAD

**Issue by allardnaber** [rijksuniversiteit-groningen/b2-AssessmentTools#112]
De submissions van een essay assignment kunnen worden gedownload naar html-bestanden, met een header hierin. Wanneer je dit wilt gebruiken voor een Ephorus-scan leidt dit dus altijd tot hoge percentages. 
Omdat de inzendingen kunnen varieren in lengte, maar relatief kort kunnen zijn, worden de percentages met overeenkomsten onbetrouwbaar want ze vliegen alle kanten op.

(Lijkt gecombineerd met export van lege submissions helemaal tot ellende te leiden, dat test ik nog eventjes)

**Comment by magiclars-off** [comment]
Het is nu dit. Wil je een optie "Download Submissions (Ephorus)" die enkel de input van de gebruiker download?
 
![image](https://user-images.githubusercontent.com/62888804/83266931-cd1ac600-a1c3-11ea-8342-dcfbf3e1d27c.png)

**Comment by magiclars-off** [comment]
https://github.com/rijksuniversiteit-groningen/buildingblocks/pull/1411
