### ISSUE TITLE
how to use Include HTML/JS PDF viewer?

### ISSUE THREAD

**Issue by blmi** [rijksuniversiteit-groningen/b2-AssessmentTools#49]
how can/must we use this viewer at the Hanze BB environment? Is their an instruction?

**Comment by jasper-smit** [comment]
@allardnaber als je toch instructies al hebt, Kan je het mij ook sturen? Dan steek ik het ook in een readme ergens op github.

**Comment by allardnaber** [comment]
- Ga naar de Content Collection en maak een nieuwe map PDF aan.
- Manage permissions voor de folder PDF door op het handje te klikken.
- Kies voor Select Specific Users by place > Course
- Zoek voor je eigen course en kies bij rollen: All Course Users en permission: read
- Upload in de PDF map een PDF-bestand (Upload > Upload Files). Door het ín de PDF-map toe te voegen, hoef je maar 1x de permissie erop te zetten in plaats van per bestand.
- Ga naar http://www.allardnaber.nl/uocg/pdfs.php

Wil je 1 PDF link maken: 
- ga naar de content collectie van het tentamen
- klik met je rechter muis op de pdf titel en selecteer copy shortcut (Internet Explorer) of Copy link location 
- plak deze link in het de eerste text box op de website
- klik op GO
- kopieer de groene regel 
- Ga naar de exam/tentamen map en naar het item/essay vraag waar je de pdf wilt invoegen. Klik op de knop 'html' en plak hier het gekopieerde stuk.

Wil je meerdere PDF's gebruiken:
- ga naar de content collectie van het tentamen
- klik op een willekeurige PDF in de map PDF met je rechter muis op de pdf titel en selecteer copy shortcut (Internet Explorer) of Copy link location > dit is nodig zodat het tooltje weet voor welke cursus je de PDF links wilt maken. 
- selecteer alle PDF's en klik op Download package (je krijgt nu een ZIP bestand)
- ga naar de gedownloade PDF map, klik met je rechtermuisklik erop en kies voor extract all/ uitpakken 
- klik in de uitgepakte map met ALT + SHIFT + Rechter muisklik > kies voor: open command window here
- typ hier: dir /B > files.txt en klik op enter
- je hebt nu een txt bestand gekregen met de  titel: files.txt
- open dit bestand en kopieer alles
- plak dit in het 2e textvak en klik op GO
- kopieer alle groene regels 
- Ga naar de exam/tentamen map en plak het in de toets waar je het wilt hebben. Open in de Editor de HTML-modus en plak hier de gekopieerde code. De PDF-jes komen dan als opsomming van linkjes in het item te staan.

**Comment by allardnaber** [comment]
> @allardnaber als je toch instructies al hebt, Kan je het mij ook sturen? Dan steek ik het ook in een readme ergens op github.

staat op de wiki ;)
