### ISSUE TITLE
Print option in 'manage submission' overview. 

### ISSUE THREAD

**Issue by Josiendeboer** [rijksuniversiteit-groningen/b2-AssessmentTools#59]
Click on the submissions of an essay question. There is an option 'print' in the manage submissions overview. However when you click on a few students and then click on print button you get to the general print screen and not the print of the selection of those students. 
We would like to use this option, because this the only option to see all the answers of the student who did use the option 'do not review'.

**Comment by allardnaber** [comment]
This is an action button, not related to the list. There's this option that should do the same?
![image](https://user-images.githubusercontent.com/11871362/68319626-ec82c200-00be-11ea-8f23-d15c4d59f849.png)
