### ISSUE TITLE
Print Blackboard test with Pools: no images

### ISSUE THREAD

**Issue by Josiendeboer** [rijksuniversiteit-groningen/b2-AssessmentTools#61]
Go to an assessment folder > make a print of a blackboard test with a pool and MC questions that contains pictures > the pictures are not printed.

**Comment by jasper-smit** [comment]
Dit blijkt een ander probleem te zijn, namelijk dat de vragen uit de question set niet getrokken worden. Wordt opgelost in de volgende release.
