### ISSUE TITLE
Scrollen in gradevakje

### ISSUE THREAD

**Issue by allardnaber** [rijksuniversiteit-groningen/b2-AssessmentTools#72]
Wanneer je muis op het gradevakje staat (grading essays) en je wil de pagina naar beneden of boven scrollen, scroll je eerst het cijfer naar 0 of naar de maximale score voordat de pagina scrollt. Omdat dit snel achter elkaar door gaat zul je niet in de gaten hebben dat je het cijfer onbewust hebt aangepast.

Graag de scrolloptie uitschakelen in het cijfervakje.

**Comment by jasper-smit** [comment]
Could not reproduce
