### ISSUE TITLE
Mark Scheduled Exam as 'Test'

### ISSUE THREAD

**Issue by allardnaber** [rijksuniversiteit-groningen/b2-AssessmentTools#77]
Add a tickbox to the scheduled exam in the Assessment Tools scheduling to indicate the exam is being tested. This does not grant access for support. 
This way, it is assured that only current exams are accessible, not future exams.

Idea: remove Scheduling permissions from support role, so they are not able to change the tick box or schedule new exams. Downside: a full-time staff member should always be standby in case things are not configured properly, or if things should be tested, etc.

**Comment by jasper-smit** [comment]
Wie is mark
