### ISSUE TITLE
Tool 'Tests' wordt niet afgeschermd

### ISSUE THREAD

**Issue by allardnaber** [rijksuniversiteit-groningen/b2-AssessmentTools#78]
Als in een examencursus gebruik wordt gemaakt van de Blackboard Tests dan blijven deze gewoon toegankelijk. 

Als je de course id van een toetscursus plakt in https://testportal.rug.nl/webapps/assessment/do/authoring/viewAssessmentManager?assessmentType=Test&course_id=_xxxx_1 , dan werkt de afscherming niet.

Idee is om het filter dat nu alleen in Assessment Folder werkt uit te breiden met /assessment?

Alternatief: alles op basis van course id filteren, maar dan moeten er uitzonderingen worden gemaakt voor de beheerportal (en user management??).

**Comment by jasper-smit** [comment]
Ik kies er voor nu voor om alles op course_id te laten werken
